coverage:
  status:
    project:
      default:
        target: 5%
        threshold: 5%
        if_ci_failed: ignore
    patch:
      default:
        target: 5%
        threshold: 5%
        if_ci_failed: ignore

comment:
  layout: "reach, diff, flags, files"
  behavior: default

ignore:

  # skip third-party dependencies and test path
  - "test/*"
  - "cmd/*"
  - "tools/*"
  - "pkg/iptables/*"
  - "pkg/ipset/*"
  - "pkg/ethtool/*"
  - "pkg/lock/*"
